### ISSUE TITLE
Suggestion or Error: Figure 5.11 unexpected IDF values

### ISSUE THREAD

**Issue by pauljurczak** [smassung/text-data-book-comments#6]
Figure 5.11 shows unexpected IDF values, which don't correspond to the example discussed in section 5.4. Based on that example and assuming base 2 logarithms, the IDF values should be: 
`[log2(6/5), log2(6/2), log2(6/3), log2(6/4), log2(6/2)]`
which is about:
`[0.3, 1.6, 1, 0.6, 1.6]`
These values change the ranking and remove the problem of d5 being a top rank.

There is a discussion about on Coursera forum under [IDF weighting](https://class.coursera.org/textretrieval-001/forum/thread?thread_id=374#post-945), but no answer from the staff. There are suggestions that IDF values were calculated based on larger set of documents or perhaps other words in {d1, ..., d5}, which are not shown on the figures for brevity. If that's the case, I think it should be stated clearly, otherwise most readers will assume C = {d1, ..., d5} and all of the words from the query present in documents d1, ..., d5 are shown on the figures.

**Comment by smassung** [comment]
Hmm, I think those values seem unexpected because we don't know (as the reader) how many total documents there are in the index or what each term's document frequency is. I see how it would be confusing as we only mention documents 1 through 5, though I assume there are many more than 5 total documents.

While talking about the figure, I suggest a fix of clarifying that there are _M_ total documents in the index, where _M_ is significantly larger than 5. Then, I can create an example to calculate the IDF score for _news_, such that _IDF(news) = 1.5 = log_2 ((M+1) / df(news))_. The same thing can be done for _about_, etc.

What do you think?

**Comment by pauljurczak** [comment]
That would solve the problem and put all conspiracy theories about origin of these numbers to sleep. It would help to make clear `the whole collection` you are referring to in:

>  If you count the occurrence of the word in the whole collection, then we would see that about has
> a much higher count than presidential.

is much larger than C = {d1, ..., d5}, otherwise above sentence may not be true.

**Comment by smassung** [comment]
Excellent, thanks for the feedback! I will edit it in the next day or two.

**Comment by smassung** [comment]
The latest update should address this. If all looks good to you, I'll close the issue.

**Comment by pauljurczak** [comment]
Looks good, thank you.
